# name: Push-to-EC2

# on: push

# jobs:
#   deploy:
#     name: Push to EC2 Instance
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v1

#       - name: Deploy to my EC2 instance
#         uses: easingthemes/ssh-deploy@v2.1.5
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#           SOURCE: "./"
#           REMOTE_HOST: "ec2-54-166-235-89.compute-1.amazonaws.com"
#           REMOTE_USER: "ubuntu"
#           TARGET: "/var/html/html"


name: deploy-to-eb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm install --force

      - name: Prebuild
        run: npm run prebuild

      - name: Build
        run: npm run build

      - name: Deploy to my EC2 instance
        env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            SOURCE: "./"
            REMOTE_HOST: "ec2-54-166-235-89.compute-1.amazonaws.com"
            REMOTE_USER: "ubuntu"
            TARGET: "/var/html/html"

      